### ISSUE TITLE
Encode sample CSA document 

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-samples-csa#1]
This is one of my documents for encoding.

[CSA DSO Information Security Management through Reflexive Security.pdf](https://github.com/metanorma/mn-samples-csa/files/4332665/CSA.DSO.Information.Security.Management.through.Reflexive.Security.pdf)

Ping @manuel489 do you have time for this? Thanks!

**Comment by manuelfuenmayor** [comment]
Ok @ronaldtse !

**Comment by manuelfuenmayor** [comment]
I have encoded the document but not been able to compile it. I'm getting an error. I have informed @opoudjis already.

**Comment by manuelfuenmayor** [comment]
Encoded sample added in: https://github.com/metanorma/mn-samples-csa

*Comments:*
- Authors info is not shown in output. (I used the `:fullname:` attribute markup)
- *Introduction* is the only section that is not numbered in output. It seems to be located in the "preface" area.
- The original document doesn't show a `docnumber`.

**Comment by ronaldtse** [comment]
> Authors info is not shown in output. (I used the :fullname: attribute markup)

@opoudjis we need to update the bibdata model.

> Introduction is the only section that is not numbered in output. It seems to be located in the "preface" area.

Let's use the ISO style: when it has sub-clauses, number it as 0. Otherwise, don't number it.

> The original document doesn't show a docnumber.

This is a flaw of the CSA document model. I will address this.

**Comment by opoudjis** [comment]
>> Authors info is not shown in output. (I used the :fullname: attribute markup)
> @opoudjis we need to update the bibdata model.

There has never been provision for CSA documents to include personal authors. If you want that done, you (a) confirm it with CSA, and (b) MAKE A TICKET. I will not action something something like this on a casual at-mention.

**Comment by manuelfuenmayor** [comment]
This ticket remains on hold until https://github.com/metanorma/metanorma-csa/issues/31 get closed.

**Comment by opoudjis** [comment]
You will also need its PDF counterpart, https://github.com/metanorma/metanorma-csa/issues/45

**Comment by manuelfuenmayor** [comment]
This document is fully encoded and it's looking good except for a minor detail that I'll post in a ticket apart. Closing
